version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    depends_on:
      - playapp


  playapp:
    build: .
    expose:
      - "9000"
    depends_on:
      - mongodb
    command: "/rizwan/play-lb-scheduler/bin/play-lb-scheduler"
    stdin_open: true

  mongodb:
    image: mongo:4.2.1
    environment:
      MONGO_INITDB_DATABASE: scheduler
      MONGO_INITDB_ROOT_USERNAME: rizwan
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
    ports:
      - "27017:27017"
